version: "2"
services:
  nlp-py:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    image: sk532359025/nlp_py
    volumes:
      - ./log:/nlp_model/log
    command: 
      - sh
      - -c
      - |
        gunicorn main:app -c gunicorn.conf.py \
        --access-logfile=/nlp_model/log/access_print.log \
        --error-logfile=/nlp_model/log/error_print.log
    ports:
      - "9523:8000"
    tty: true
    environment:
      - ENV=prod
      - CONFIG_PATH=/code
    container_name: nlp-py
