version: "2"
services:
  nlp-py:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    image: nlp-py:1.0
    volumes:
      - .:/code
    command: 
      - sh
      - -c
      - |
        python3 -m pip install --upgrade pip
        pip install -i https://pypi.tuna.tsinghua.edu.cn/simple numpy
        pip install -i https://pypi.tuna.tsinghua.edu.cn/simple uwsgi
        pip install -i https://pypi.tuna.tsinghua.edu.cn/simple pandas
        pip install -i https://pypi.tuna.tsinghua.edu.cn/simple gensim
        pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
        uwsgi -i uwsgi.ini
    ports:
      - "9523:8000"
    tty: true
    environment:
      - env=prod
    container_name: nlp-py
